#!/usr/bin/env python3
"""Generate Table I from the selected multi-seed sparsity result cache."""

from __future__ import annotations

import csv
import os
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
CACHE = Path(
    os.environ.get(
        "SPARSITY_RESULTS_CACHE",
        str(REPO / "artifacts" / "paper-release" / "evaluation" / "cache" / "manuscript"),
    )
).resolve()
PAPER = Path(
    os.environ.get("SPARSITY_PAPER_DIR", str(REPO / "reproduced" / "manuscript"))
).resolve()
SOURCE = (
    CACHE
    / "tables"
    / "multiseed_new_table1_breakdown035_weighted_degradation_mean_std.csv"
)
OUTPUT = PAPER / "table1" / "tabular_multiseed_vmae_rmse.tex"

MODELS = ["DCRNN", "D2STGNN", "Mamba4Traffic", "Trafformer"]
METRICS = [
    ("bar_vMAE", r"$\bar{v}$MAE", False),
    ("bar_D_MAE", r"$\bar{D}_{MAE}$", True),
    ("bar_vRMSE", r"$\bar{v}$RMSE", False),
    ("bar_D_RMSE", r"$\bar{D}_{RMSE}$", True),
]
VALUE_COLUMNS = [
    "PEMS04_Flow",
    "PEMS04_Occ",
    "PEMS04_Speed",
    "PEMS04_Avg",
    "PEMS08_Flow",
    "PEMS08_Occ",
    "PEMS08_Speed",
    "PEMS08_Avg",
]


def load_rows() -> dict[tuple[str, str], dict[str, str]]:
    with SOURCE.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    indexed = {(row["Model"], row["metric_row"]): row for row in rows}
    missing = [
        f"{model}/{metric}"
        for model in MODELS
        for metric, _, _ in METRICS
        if (model, metric) not in indexed
    ]
    if missing:
        raise RuntimeError(f"Missing Table I rows in {SOURCE}: {', '.join(missing)}")
    return indexed


def number(value: float, degradation: bool) -> str:
    return f"{value:.2f}$\\times$" if degradation else f"{value:.3f}"


def styled_values(
    rows: dict[tuple[str, str], dict[str, str]], metric: str, degradation: bool
) -> dict[str, list[str]]:
    styled = {model: [""] * len(VALUE_COLUMNS) for model in MODELS}
    for column_index, column in enumerate(VALUE_COLUMNS):
        values = [float(rows[(model, metric)][column]) for model in MODELS]
        order = sorted(range(len(MODELS)), key=lambda idx: values[idx])
        best, second = order[0], order[1]
        for model_index, model in enumerate(MODELS):
            value = number(values[model_index], degradation)
            if model_index == best:
                value = f"\\textbf{{{value}}}"
            elif model_index == second and abs(values[best] - values[second]) > 1e-12:
                value = f"\\underline{{{value}}}"
            std = float(rows[(model, metric)][f"{column}_std"])
            styled[model][column_index] = (
                r"\begin{tabular}[t]{@{}c@{}}"
                + value
                + r" \\[-0.05ex] {\fontsize{6}{7}\selectfont \hspace{0.45em}$\pm$"
                + f"{std:.3f}"
                + r"}\end{tabular}"
            )
    return styled


def main() -> None:
    rows = load_rows()
    rendered = {
        metric: styled_values(rows, metric, degradation)
        for metric, _, degradation in METRICS
    }
    lines = [
        "% Auto-generated by scripts/generate_table1_multiseed.py — do not edit by hand.",
        "% Standardized-input checkpoints; Gaussian weights over 0--35% sparsity.",
        "% Mean with sample standard deviation over mask seeds 43--45.",
        "",
        r"    \begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}cccccccccc@{}}",
        r"    \hline",
        r"    \multicolumn{2}{c}{Dataset} & \multicolumn{4}{c}{PEMS04} & \multicolumn{4}{c}{PEMS08} \\ \hline",
        r"    Model & Metric & Flow & Occupancy & Speed & \multicolumn{1}{c}{Avg} & Flow & Occupancy & Speed & Avg \\ \hline \\[0.9em]",
    ]
    for model_index, model in enumerate(MODELS):
        for metric_index, (metric, label, _) in enumerate(METRICS):
            prefix = rf"    \multirow{{4}}{{*}}{{{model}}} & " if metric_index == 0 else "    & "
            cells = " & ".join(rendered[metric][model])
            lines.append(prefix + label + " & " + cells + r" \\")
            if metric_index in (0, 2):
                lines.append(r"    \noalign{\vskip 0.45em}")
            elif metric_index == 1:
                lines.append(r"    \noalign{\vskip 0.9em}")
        if model_index < len(MODELS) - 1:
            lines.append(r"    \\[0.1em] \hline \\[0.9em]")
        else:
            lines.append(r"    \\[0.1em] \hline")
        lines.append("")
    lines.extend([r"    \end{tabular*}", ""])
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
